##################################################
## "build" stage
##################################################

FROM mirror.gcr.io/denoland/deno:debian-2.6.9@sha256:2221eafd8a7556693307ad9889a79d4974e1844a6964acbe466ab9faa15d37bf AS build

ENV DENO_DIR=/deno
ENV PATH=${DENO_DIR}/bin:${PATH}
ENV NITRO_PRESET=deno_server

WORKDIR /src/

COPY ./package.json ./pnpm-lock.yaml ./pnpm-workspace.yaml /src/

RUN --mount=type=cache,id=deno,dst=/deno/deps/ \
	deno install --node-modules-dir=auto

COPY ./ /src/

RUN --network=none \
	--mount=type=cache,id=deno,dst=/deno/deps/ \
	deno task prepare && deno task build

##################################################
## "main" stage
##################################################

FROM gcr.io/distroless/cc-debian13:nonroot@sha256:84fcd3c223b144b0cb6edc5ecc75641819842a9679a3a58fd6294bec47532bf7 AS main

ENV NUXT_DATABASE_URL=file:///tmp/pglite
ENV DENO_DIR=/tmp/deno

COPY --from=build --chown=0:0 /usr/bin/deno /deno
COPY --from=build --chown=0:0 /src/.output/ /capek/
COPY --from=build --chown=0:0 /src/bin/ /capek/server/bin/

WORKDIR /capek/server/

HEALTHCHECK --start-period=60s --start-interval=5s --interval=30s --timeout=5s --retries=2 \
	CMD ["/deno", "run", "--allow-net=localhost:3000", "/capek/server/bin/healthcheck.mjs", "http://localhost:3000"]

ENTRYPOINT ["/deno", "run", \
	"--allow-read=/capek/", \
	"--allow-read=/tmp/", \
	"--allow-write=/tmp/", \
	"--allow-net", \
	"--allow-env", \
	"--allow-sys", \
	"/capek/server/bin/entrypoint.mjs", \
	"/capek/server/index.mjs" \
]
