minimumReleaseAge: 10080
trustPolicy: "no-downgrade"
trustPolicyExclude:
  - "semver@6.3.1" # TODO: update to 7.x when possible
strictDepBuilds: true
allowBuilds:
  "@parcel/watcher": true
  "esbuild": true
  "sharp": true
  "unrs-resolver": true
  "vue-demi": true
overrides:
  "@types/parse-path": "-" # Deprecated
