minimumReleaseAge: 10080
trustPolicy: "no-downgrade"
strictDepBuilds: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "sharp"
  - "unrs-resolver"
  - "vue-demi"
trustPolicyExclude:
  - "chokidar@4.0.3" # TODO: update to 5.x when possible
  - "semver@6.3.1" # TODO: update to 7.x when possible
overrides:
  "@types/parse-path": "-" # Deprecated
