export function buildTriagePrompt(
  instructions: string,
  specialists: { id: string; name: string; description: string }[],
): string {
  return [
    instructions,
    "",
    "Available specialists:",
    specialists.map((s) => `- "${s.id}": ${s.name}${s.description ? ` - ${s.description}` : ""}`).join("\n"),
    "",
    'You must analyze the user\'s request and select the most appropriate specialist using the "route_to_specialist" tool.',
  ].join("\n");
}

export function buildSkillToolsPrompt(): string {
  return [
    "## Available skills",
    "",
    "Tools prefixed with `skill_` are pre-built, tested operations designed to simplify common tasks.",
    "**Prefer skill tools over other tools when they can accomplish the task.**",
  ].join("\n");
}

export function buildCodeInterpreterPrompt(): string {
  return [
    "## Code execution environment",
    "",
    "JavaScript sandbox accessed via the `execute_code` tool.",
    "",
    "### Key rules",
    "",
    "- Code is already `async` wrapped, use `await` directly.",
    "- Use `return` for results, use `console.log` for debugging.",
    "- No `require`, static `import`, `process` or external modules (except `/skills/` & `/servers/`).",
    "",
    "### File system",
    "",
    "- Global `fs` object (do not `import` or `require`). Compatible with Node.js `fs` API.",
    "- Methods: `exists`, `stat`, `readFile`, `readdir`, `glob`, `mkdir`, `writeFile`, `appendFile`, `copyFile`, `unlink`, `rmdir`, `rename`, `rm`.",
    "- Usage: `fs.<method>Sync(...)` or `await fs.promises.<method>(...)`.",
    "- Paths:",
    "  - `/skills/`: reusable skills with code and documentation.",
    "  - `/servers/`: raw MCP tools (use if no suitable skill exists).",
    "  - `/workspace/`: persists between executions. READ/WRITE here.",
    "",
    "### Skills structure",
    "",
    "```",
    "/skills/",
    "├── index.js          # Main entry: const { $skillName } = await import('/skills/index.js')",
    "└── runBrowserScript/ # Specific skill directory",
    "    ├── SKILL.md      # Read for usage documentation",
    "    └── scripts/",
    "        └── main.js   # Skill implementation",
    "```",
    "",
    "### Examples",
    "",
    "Discover & Use:",
    "```js",
    "// 1. Explore",
    "fs.readdirSync('/skills');",
    "fs.readFileSync('/skills/runBrowserScript/SKILL.md');",
    "",
    "// 2. Execute",
    "// Prefer skills when available",
    "const { $runBrowserScript } = await import('/skills/index.js');",
    "return await $runBrowserScript({ code: 'async (page) => { return page.title(); }' });",
    "",
    "// Or use raw tools directly",
    "const { $browser_navigate } = await import('/servers/Playwright/index.js');",
    "return await $browser_navigate({ url: 'https://example.com' });",
    "```",
    "",
    "Create reusable modules (CRITICAL: export functions, DO NOT auto-execute):",
    "```js",
    "fs.writeFileSync('/workspace/analyze.js', `",
    "export default function analyze(data) { return data.length; }",
    "`);",
    "",
    "// Import and run explicitly",
    "const { default: analyze } = await import('/workspace/analyze.js');",
    "return analyze([1, 2, 3]);",
    "```",
    "",
    "### Tips",
    "",
    "- **Read before running**: checking `SKILL.md` or JSDoc prevents errors.",
    "- **Modularize**: save complex logic to `/workspace/` to keep the context clean.",
    "- **Avoid auto-execution**: reusable files should only define exports, never run code at top-level.",
  ].join("\n");
}
